name: Code Execution Service CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-execution-service-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build
        run: |
          cd code-execution-service
          go build -v ./...

      - name: Test
        run: |
          cd code-execution-service
          go test -v ./...